### ISSUE TITLE
Missing file install/upgrade/upgrade.php

### ISSUE THREAD

**Issue by muyncky** [blauwfruit/juice#32]
Calling `Install/upgrade/upgrade.php` within juice is not working, gives a 404, because it is not there.

**Comment by muyncky** [comment]
Found a resource: https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/#database-upgrade

**Comment by muyncky** [comment]
I've been trying many things with the autoupgrade cli tool, but no success, the databse does not upgrade. I get an exception:

```
INFO - === Step upgradeDb
INFO - Cleaning file cache
INFO - Running opcache_reset
NOTICE - [INTERNAL] /var/www/html/config/defines_custom.inc.php line 27 - Constant _PS_MODE_DEV_ already defined
INFO - Initializing required environment constants
INFO - Checking version validity
INFO - Checking connection to database
INFO - Disabling all non native modules
INFO - Updating database data and structure
WARNING - 
            <div class="upgradeDbError">
            [WARNING] SQL 8.1.7
            1054 in ALTER TABLE `ps_category_lang` CHANGE `additional_description` `additional_description` MEDIUMTEXT: Unknown column 'additional_description' in 'ps_category_lang'</div>
WARNING - 
            <div class="upgradeDbError">
            [WARNING] SQL 8.1.7
            1054 in ALTER TABLE `ps_orders` CHANGE `note` `note` MEDIUMTEXT: Unknown column 'note' in 'ps_orders'</div>
INFO - Running generic queries
INFO - Database upgrade OK
INFO - Upgrading languages
INFO - Regenerating htaccess
INFO - Cleaning XML files
INFO - Keeping overrides in place
INFO - Upgrade the RTL files of back-office themes.
INFO - Upgrade the RTL files of front-office themes.
INFO - Switching to default theme.
CRITICAL - [INTERNAL] /var/www/html/src/Core/Addon/Theme/ThemeManager.php line 398 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details.
#0 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(255): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array)
#1 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(86): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic')
#2 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(731): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic')
#3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(710): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->switchToDefaultTheme()
#4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(151): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme()
#5 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#6 /var/www/html/modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
#7 /var/www/html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->run()
#8 /var/www/html/modules/autoupgrade/cli-upgrade.php(50): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run()
#9 {main}
CRITICAL - [INTERNAL] /var/www/html/src/Core/Addon/Theme/ThemeManager.php line 398 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details.
#0 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(255): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array)
#1 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(86): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic')
#2 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(731): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic')
#3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(710): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->switchToDefaultTheme()
#4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(151): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme()
#5 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
#6 /var/www/html/modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
#7 /var/www/html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->run()
#8 /var/www/html/modules/autoupgrade/cli-upgrade.php(50): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run()
#9 {main}

```

**Comment by muyncky** [comment]
> I've been trying many things with the autoupgrade cli tool, but no success, the databse does not upgrade. I get an exception:
> 
> 
> 
> ```
> 
> INFO - === Step upgradeDb
> 
> INFO - Cleaning file cache
> 
> INFO - Running opcache_reset
> 
> NOTICE - [INTERNAL] /var/www/html/config/defines_custom.inc.php line 27 - Constant _PS_MODE_DEV_ already defined
> 
> INFO - Initializing required environment constants
> 
> INFO - Checking version validity
> 
> INFO - Checking connection to database
> 
> INFO - Disabling all non native modules
> 
> INFO - Updating database data and structure
> 
> WARNING - 
> 
>             <div class="upgradeDbError">
> 
>             [WARNING] SQL 8.1.7
> 
>             1054 in ALTER TABLE `ps_category_lang` CHANGE `additional_description` `additional_description` MEDIUMTEXT: Unknown column 'additional_description' in 'ps_category_lang'</div>
> 
> WARNING - 
> 
>             <div class="upgradeDbError">
> 
>             [WARNING] SQL 8.1.7
> 
>             1054 in ALTER TABLE `ps_orders` CHANGE `note` `note` MEDIUMTEXT: Unknown column 'note' in 'ps_orders'</div>
> 
> INFO - Running generic queries
> 
> INFO - Database upgrade OK
> 
> INFO - Upgrading languages
> 
> INFO - Regenerating htaccess
> 
> INFO - Cleaning XML files
> 
> INFO - Keeping overrides in place
> 
> INFO - Upgrade the RTL files of back-office themes.
> 
> INFO - Upgrade the RTL files of front-office themes.
> 
> INFO - Switching to default theme.
> 
> CRITICAL - [INTERNAL] /var/www/html/src/Core/Addon/Theme/ThemeManager.php line 398 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details.
> 
> #0 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(255): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array)
> 
> #1 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(86): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic')
> 
> #2 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(731): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic')
> 
> #3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(710): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->switchToDefaultTheme()
> 
> #4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(151): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme()
> 
> #5 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
> 
> #6 /var/www/html/modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
> 
> #7 /var/www/html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->run()
> 
> #8 /var/www/html/modules/autoupgrade/cli-upgrade.php(50): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run()
> 
> #9 {main}
> 
> CRITICAL - [INTERNAL] /var/www/html/src/Core/Addon/Theme/ThemeManager.php line 398 - PrestaShop\PrestaShop\Core\Domain\Theme\Exception\FailedToEnableThemeModuleException: Unfortunately, the module did not return additional details.
> 
> #0 /var/www/html/src/Core/Addon/Theme/ThemeManager.php(255): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array)
> 
> #1 /var/www/html/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(86): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic')
> 
> #2 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(731): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic')
> 
> #3 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(710): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->switchToDefaultTheme()
> 
> #4 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(151): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme()
> 
> #5 /var/www/html/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader81.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade()
> 
> #6 /var/www/html/modules/autoupgrade/classes/Task/Upgrade/UpgradeDb.php(49): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader81->doUpgrade()
> 
> #7 /var/www/html/modules/autoupgrade/classes/Task/Runner/ChainedTasks.php(61): PrestaShop\Module\AutoUpgrade\Task\Upgrade\UpgradeDb->run()
> 
> #8 /var/www/html/modules/autoupgrade/cli-upgrade.php(50): PrestaShop\Module\AutoUpgrade\Task\Runner\ChainedTasks->run()
> 
> #9 {main}
> 
> 
> 
> ```

This might be due to settings about switching to default theme as described here https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/use-autoupgrade-module/

**Comment by muyncky** [comment]
defining `--channel=major` will make autoupgrade module try to switch back to the default theme, this causes errors. If we define `--channel=private` this exception does not happen. Yet the database is not upgraded, it still does not contain `hook.active`.

**Comment by muyncky** [comment]
I tried copying the `install/upgrade` folder from 1.7.x into the 8.x, but it depends on `src/PrestaShopBundle/Install/Upgrade.php`, and this is not included in 8.x.
